### ISSUE TITLE
Weapon with 2 same affixes flickers

### ISSUE THREAD

**Issue by piotrszymaniec** [josdemmers/Diablo4Companion#1]
I have weapon which base has +Critical Strike Damage, it also have the same affix, it keeps switching green circle form one to other
see recording
http://g.recordit.co/yJlNzvplSP.gif

**Comment by josdemmers** [comment]
Thanks for the report.
Problem is caused because for each item type only the best matching affix is returned currently.

**Comment by josdemmers** [comment]
Fixed with Release v1.1.0.0
