### ISSUE TITLE
Custom dots colors

### ISSUE THREAD

**Issue by shampax** [josdemmers/Diablo4Companion#102]
It is posible to set custom colors for dots ? 
I'm colorblind, and i canot really diferentiate on the fly, need to look carefull on them.
Ty,

**Comment by josdemmers** [comment]
Yes you can, click on the colored section on the left side of the affixes. Opens a new window to set your color.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/56a8b87b-a78b-4056-aea8-da292bbded4a)

**Comment by shampax** [comment]
many thanks!
