### ISSUE TITLE
Request: color resistance affixes differently

### ISSUE THREAD

**Issue by adriaandavel** [josdemmers/Diablo4Companion#103]
Resistance affixes are a fluid thing. Right now my build guide could show 'Fire resistance' on pants and the app will show red for everything other than fire resistance which is technically correct. It could be however that I need Lighting Resistance in that slot as I have capped my fire resistance elsewhere and I may trash a good item that I can use as is.

Could we get a different color for resistance-type mismatches to prompt us to look at what we actually need?

**Comment by josdemmers** [comment]
For now I'll combine that with https://github.com/josdemmers/Diablo4Companion/issues/100

**Comment by josdemmers** [comment]
I see now that this a bit different than #100. Resistance is about mismatches on the same item slot and your other issue is about matches on another item slot.

For resistance I think it's best to add all resistance affixes you are interested in yourself to an item slot. And then set the color yourself.
The D4C app can only use information from the current tooltip. So unfortunately I cannot automate the process to let a user know which resistance is lacking.
