### ISSUE TITLE
Blood mist affix imported as Stunt duration D4Build

### ISSUE THREAD

**Issue by Saharash** [josdemmers/Diablo4Companion#108]
![image](https://github.com/josdemmers/Diablo4Companion/assets/34897211/9cbd143d-d360-4488-883b-2ad8f468e244)
![image](https://github.com/josdemmers/Diablo4Companion/assets/34897211/c938e18a-7bcd-47c7-a051-dbb153d38abb)
build: https://d4builds.gg/builds/ef414fbd-81cd-49d1-9c8d-4938b278e2ee/?var=0

**Comment by Saharash** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/34897211/d6434d99-50f3-443f-ad70-beff5b360f68)
And inherent affix still didn't import from d4build, last update 3.4.6.0

**Comment by josdemmers** [comment]
The Resistance to all elements only works when it's included:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/e8420ae1-c723-43a3-9de6-1c6484f0228b)

Maxroll:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/cd661b69-206f-457a-a768-30add07ca0c0)

**Comment by josdemmers** [comment]
Will have to check what is happening with the `Blood mist affix`.
Probably because the extra text d4builds uses to describe the tempered affixes.

**Comment by josdemmers** [comment]
Did some tests. Both inherent and tempered will not always work for d4builds because of the different affix descriptions they use.
That will cost some more time to get that working again.

**Comment by Saharash** [comment]
> Owner

Alright thanks !

**Comment by josdemmers** [comment]
I think I found most of the issues, got a few questions thought.

Do you know how this one looks ingame?

Diablo 4 Companion:
`Golem Cooldown Reduction (Necromancer Only)`

d4builds:
`[16 - 25%] Golem Active Cooldown Reduction (Necromancer Efficiency - Resource)`

With or without the `active` part?

And the second one, in the build you linked there is a strange tempered affix on the pants.
![Screenshot 2024-05-29 145052](https://github.com/josdemmers/Diablo4Companion/assets/8627157/37a71fe4-1a39-49e5-ae38-62df33e7b958)

Looks like two different affixes merged together? However the `Blight Slow Potency` does not exist in my data.

**Comment by Saharash** [comment]
The first answer looks like that: 
![image](https://github.com/josdemmers/Diablo4Companion/assets/34897211/bf1d5373-75ee-4e39-8258-1aeb6e1b1514)


And for the second, there is this: 
![image](https://github.com/josdemmers/Diablo4Companion/assets/34897211/f68a7a36-e89d-44f5-8e0d-fe1ad54129a2)

**Comment by josdemmers** [comment]
I think it will work good enough to find `Golem Active Cooldown Reduction` instead of `Golem Cooldown Reduction`.
But will need to look into that later why my text is different.

> And for the second, there is this:

So a bug on d4builds then? Looks like the added the whole temper manual instead of a single affix.

**Comment by josdemmers** [comment]
> But then I'll still need to find that Blight Slow Potency affix. Although I'm sure I have added all tempered affixes I could find in the data.

Found it, it's one of those affixes that is saved differently in the data. There are about 30+ more affixes like that. Still need to figure out how to get those.
So the next update will fix most of your issues but the `Blight Slow Potency` will have to wait.

**Comment by josdemmers** [comment]
With v3.4.7.0 you will be able to import the tempered affixes.
`Blight Slow Potency` will follow later.

**Comment by Saharash** [comment]
> With v3.4.7.0 you will be able to import the tempered affixes. `Blight Slow Potency` will follow later.

Thanks sir, i have see also like 3 different affix that was bad imported, i don't remember them all but i know one is on this build:

Weapons is importing Attack speed at tempered affix, but it's MINION attack speed.

And for the others i have to check if i can remember, but yeah there was more bad imported, i let you know

**Comment by Saharash** [comment]
Edit: Minion attack speed got fixed in the last version, will let you know if i find wrong values, thanks for the update!

**Comment by josdemmers** [comment]
No problem, let me know when you find any.
For the `ef414fbd-81cd-49d1-9c8d-4938b278e2ee` build the only one left is the `Blight Slow Potency`.

> they changed icon of greater affix, and all greater affix aren't recognized anymore with diablo companion

Fixed that this morning for all the 1080p and 1440p system presets. Should work again if you update the system preset under settings.

**Comment by Saharash** [comment]
Alright thanks sir i didn't updated i thought it was automatically done.

I have a pretty nice suggestion, i don't know if it would be possible but:

It would be great if we can set different affix for Ring 1 and Ring 2, same for all different weapons from barbarian, because we need 4 different weapons but affix is show same for all

**Comment by josdemmers** [comment]
You could try to do that by using different colors for the affixes.

**Comment by josdemmers** [comment]
Added the missing Blight Slow Potency as well. Will be available in the next release.
