### ISSUE TITLE
works wrong

### ISSUE THREAD

**Issue by Xinelin** [josdemmers/Diablo4Companion#11]
Tools makes some wrong
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/9975dd6b-6d4c-4d2f-9ab3-d0f19e034482)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/b4ddfe2f-8d88-451e-b5b8-a7a14ee3e1ff)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/93d4be68-e94b-4d73-a27d-29e72636e6a5)
Affixes are all matched but tool show red dots
Idn why,how to fix it

**Comment by josdemmers** [comment]
Looks like there are multiple red dots on top of each other. Probably some green as well.
Could you make a screenshot of the other debug images as well?
Especially the one showing the detected affix locations.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/4bf8a08c-5966-48d4-88aa-655a6b1b8900)

**Comment by Xinelin** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/5d68fea1-a38d-495f-8f64-e48b7113dedb)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/1ad52b0f-4e07-40b3-90ea-937ff085312e)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/57223026-faf8-4c85-89f2-6a5463535cea)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/72d68339-699d-4120-a52f-24b5057a32ad)

**Comment by josdemmers** [comment]
Think I found it. It's because the Chinese font is very large.
See the orange arrow in my image? That distance is too big.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/380ba5ca-d035-410f-aea1-b565808cb828)

**Comment by josdemmers** [comment]
Will try to fix this in the next version. Around Friday/Saturday I think.

**Comment by josdemmers** [comment]
Maybe you can even solve it yourself if you create a new `dot-affixes_1.png` and `dot-affixes_2.png`.
Not working for you:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/8b4384d6-854c-4a8c-8517-df83d4faa306)

Might work:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/027db75c-8b8f-4f4f-839f-8cbcce6b0a33)

Idea is to make it higher to match your font height.

**Comment by Xinelin** [comment]
i find new way too solve the bug
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/8840eeba-65de-4bac-a2b4-6272359e5994)

**Comment by josdemmers** [comment]
Nice workaround, that will work in a lot of cases. But not every affix will start with a "+".

I found another solution that should work for all cases.
Could you send me a fullscreen screenshot without any red/green dots? Then I can do some tests.

**Comment by Xinelin** [comment]
I found that this method does have some small problems
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/dc8b379a-3c69-4e17-a723-1b9fb8c324dc)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/3e91db50-154d-4e4c-badd-a8e9a30c0de0)
there are two pics

**Comment by josdemmers** [comment]
Could you send the complete ingame screenshot as well? Makes it easier to do some tests.

**Comment by Xinelin** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/0f8e1fb0-1748-47fe-9826-caab413b2f30)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/a2bfe6d8-0fb7-48c9-9a92-456bba63305a)

**Comment by josdemmers** [comment]
Thank you, will let you know when the new version is ready.

**Comment by Xinelin** [comment]
thank you.if i am free i'll snap some zh-cn in 3440*1440 res affixes

**Comment by Xinelin** [comment]
[3440x1440_SLF_zh-CN.zip](https://github.com/josdemmers/Diablo4Companion/files/12036321/3440x1440_SLF_zh-CN.zip)
that's zh-cn Tooltips & Types snappings in 3440*1440 res
what can help you to build localization

**Comment by josdemmers** [comment]
Thanks that preset made testing easier
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/23fbbe4a-090a-486d-a152-2ee47cb64a53)

Still working on a few other bugs, next version should be ready this weekend.

**Comment by josdemmers** [comment]
Regarding your tooltip images, you only need the `shift` one. Can delete all others.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/14762ec0-4fd0-45b9-a5e8-f7e15c082968)

**Comment by josdemmers** [comment]
Fixed in the v1.1.5.0 release.

**Comment by Xinelin** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/6666300e-b468-44f3-b5a5-96da28eea6e7)
it seems not perfect

**Comment by josdemmers** [comment]
That is another problem caused by the affix location images.
You can ignore my previous example of the `dot-affixes_1.png`.
The image shouldn't contain as less background as possible.

Correct:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/720fd700-dea7-4f43-a0c3-8ad07fb69318)

Wrong:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/9e8a4849-632d-40d3-8d78-a9fb20ac7931)

Wrong:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/ead2e705-e12e-4877-9ec8-11515d9f586c)

**Comment by Xinelin** [comment]
![Uploading image.png…]()
OK PERFECT I snapped and edit with Photoshop then it's working.

**Comment by Xinelin** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/7a4f90ea-424e-49a7-951f-ed473209b92d)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/cf2425f3-65b7-44ae-a344-f2d3af55954c)
npc shop BUG
But the feeling will not affect the use

**Comment by Xinelin** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/18f08819-53ec-4620-8045-3af8a700d4e6)
![image](https://github.com/josdemmers/Diablo4Companion/assets/43874766/f73dee39-0eca-4ad3-84ec-e6b4d5661d03)

bag items bug maybe cause by height value

**Comment by josdemmers** [comment]
I have some ideas to improve it. Will try it in the next version.

**Comment by josdemmers** [comment]
Made some improvements in v1.1.6.0

**Comment by Xinelin** [comment]
1.1.6 seems more smart than before 
fast response now
If there is a BUG, I will continue to report back.
