### ISSUE TITLE
 Invalid windowHandle - Steam_Chinese version(simplified)

### ISSUE THREAD

**Issue by hezhongtang** [josdemmers/Diablo4Companion#111]
Dear,
   App doesn't work on steamplatform D4. I guess it's the windowname problem.

Environment:Win11
Gameplatform: Steam
language: Chinese(simplified)
Error:2024-06-15 13:41:13.0553|WARN|D4Companion.Services.ScreenCaptureHandler|UpdateScreen: Invalid windowHandle. Diablo IV processes found: 0. Retry in 10 seconds.
Preset: 1440p_SMF_zh-CN

![image](https://github.com/josdemmers/Diablo4Companion/assets/33770118/b7a70e3c-8a0e-4590-904e-6be59d7c815f)

**Comment by josdemmers** [comment]
Hi @hezhongtang could you take a screenshot of the `task manager` `details` tab.
Is this also named `Diablo IV.exe` for steam?

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/fd2ff2b0-d306-4ede-a20e-715782e7e297)

And could you try if this version works for you:
https://filebin.net/p5brbcwufd7hu0l9

**Comment by hezhongtang** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/33770118/c04ae032-eebe-40f7-926d-21dcd08ca1c3)
I guess the same?

**Comment by hezhongtang** [comment]
btw, if i switch the language , the en version is working.

**Comment by hezhongtang** [comment]
3.6.3.1 is working, great job!

**Comment by josdemmers** [comment]
Thanks for testing, then it was caused by the windows title.
I'll release v3.6.4.0 in a few minutes as the official version.
