### ISSUE TITLE
Greater Affixes

### ISSUE THREAD

**Issue by mysticturtle12** [josdemmers/Diablo4Companion#118]
No matter what thresholds I set for the recognition I can't get any greater affixes to actually be recognized and have a circle next to them.

**Comment by josdemmers** [comment]
Hi @mysticturtle12 did you already check the following troubleshooting steps?
https://github.com/josdemmers/Diablo4Companion/wiki/Frequently-asked-questions#missing-greenred-dots-even-when-overlay-app-icon-is-visible

If that doesn't work can you post your debug pictures here?
There is an export button on the debug view that combines all debug pictures into one.

![image](https://github.com/user-attachments/assets/37db887e-75e0-46ce-aecf-3716f65febd6)

**Comment by mysticturtle12** [comment]
Yeah I double checked to make sure everything was correct with debug and it's only greater affixes that have the issue. Here's a debug shot of a normal and a greater item. 
![debug_1080p_SMF_en_133738292053873193](https://github.com/user-attachments/assets/93f8b10d-7834-43e2-af6f-43c13eb53bd4)
![debug_1080p_SMF_en_133738292169905716](https://github.com/user-attachments/assets/08e6a8f3-99ed-4b09-94d0-ba3c058af7a0)

**Comment by josdemmers** [comment]
Could you update the `1080p_SMF_en.zip` from the settings view to make sure you have the latest changes.
After that check if the `brightness threshold` in the app is set to 70 and 255.

![image](https://github.com/user-attachments/assets/51f3a320-91e2-4349-9e85-de2fdbebc947)

And finally reset your ingame brightness to default.

**Comment by mysticturtle12** [comment]
Alright im not sure if it was some issue with updating because I had all those settings and ingame brightness and updated and it still didn't work.

But as a last effort I tried the classic just uninstall and reinstall it and this time when i downloaded the same settings package this time it worked. So maybe it was something not updating or being replaced correctly when hitting update vs downloading it fresh?

**Comment by josdemmers** [comment]
Good to hear it's working now!
The update vs downloading of the system presets works the same. Downloads a zip file, extracts it, and replaces the files. But maybe a file was still in use somehow and it failed to update.

Other possibility is that one of the `Similarity Thresholds` in the debug view had a wrong value. Defaults are 0.05
