### ISSUE TITLE
Correct enchanted rolls aren't marked green

### ISSUE THREAD

**Issue by Jaeger9671** [josdemmers/Diablo4Companion#119]
If you roll the stat recommended on the build through enchanting, the stat is still marked red instead of green.

**Comment by josdemmers** [comment]
All different affix icons should work fine, i.e. normal, enchanted, tempered, greater.
Could you post your debug pictures for the item that is not working? Then I can check which part is causing problems for you.

You can find the export button here:
![377725580-37db887e-75e0-46ce-aecf-3716f65febd6](https://github.com/user-attachments/assets/c3fc7787-a6b5-4aa8-a5b6-98c5fcb1e49b)

**Comment by Jaeger9671** [comment]
Yeah for me its not marking green enchanted or greater affix items.  Attached are a few screenshots.
![debug_1440p_SMF_en_133745683189749618](https://github.com/user-attachments/assets/86876a27-cb6a-43f3-865d-8c7698ee3bf3)
![debug_1440p_SMF_en_133745684175829288](https://github.com/user-attachments/assets/f690a3cb-eb5e-4a16-9d98-1097e136e629)
![debug_1440p_SMF_en_133745685262477354](https://github.com/user-attachments/assets/5e86573f-c720-4810-9435-fb7ed15773d8)

**Comment by josdemmers** [comment]
Not sure what happened with the third picture, but looks like you selected a different system preset there or changed your monitor resolution. The tooltip width is too small.

For your first two pictures I see you are using 1440p_SMF_en, that's the one I'm using as well and it works great.
Could you follow the following troubleshooting steps first to see if that solves your issue? Most common problem is that the brightness is not set to default.

https://github.com/josdemmers/Diablo4Companion/wiki/Frequently-asked-questions#missing-greenred-dots-even-when-overlay-app-icon-is-visible

Also click the download/update button under settings to update the `1440p_SMF_en` preset to the latest version.

**Comment by Jaeger9671** [comment]
I think the preset update fixed it.  I was downloading the app update but not the preset.  Everything is working as normal now.
