### ISSUE TITLE
Is Diablo4Companion safe from ban ??

### ISSUE THREAD

**Issue by MissaSolemnis** [josdemmers/Diablo4Companion#121]
I am tired of going back and forth from time to time with alt-tap on the Max Roll homepage and Diablo 4 screen.
I think this program is my savior.
But I'm afraid I'll be banned by Blizzard.

**Comment by josdemmers** [comment]
Hi @MissaSolemnis, no worries it's safe to use. There hasn't been a single warning or ban since the start of season 1.

The app works by analyzing your screen and doesn't modify the game's data in any way.

**Comment by MissaSolemnis** [comment]
> Hi @MissaSolemnis, no worries it's safe to use. There hasn't been a single warning or ban since the start of season 1.
> 
> The app works by analyzing your screen and doesn't modify the game's data in any way.

As of today, I'm moving from hell to heaven.
Thank you so much for cool app.

**Comment by josdemmers** [comment]
You are welcome. More info about importing builds from Maxroll or other sites is on the wiki: https://github.com/josdemmers/Diablo4Companion/wiki/How-to-import-and-export-builds

Or you can join the Discord if you have any questions.
