### ISSUE TITLE
Druid landslide build images 

### ISSUE THREAD

**Issue by Delvint** [josdemmers/Diablo4Companion#14]
A zip with images for the earth bear landslide caster druid build from [IcyVeins](https://www.icy-veins.com/d4/guides/earth-bear-landslide-caster-druid-build/)

[Earth_Bear_Landslide_Caster_Druid.zip](https://github.com/josdemmers/Diablo4Companion/files/12062528/Earth_Bear_Landslide_Caster_Druid.zip)

**Comment by josdemmers** [comment]
Now included in the 2560x1440_SMF_en preset.
Made a few changes. 
- Few jpg files converted to png.
- rank of landslide.png renamed to ranks of landslide.png (and removed "ranks") from image so that it detects both rank and ranks.
