### ISSUE TITLE
`D4Companion.Updater` Error

### ISSUE THREAD

**Issue by Arborym** [josdemmers/Diablo4Companion#17]
When launching `D4Companion.Updater.exe`

![image](https://github.com/josdemmers/Diablo4Companion/assets/105245560/cb80f77b-7135-4fff-9012-a80c89f5647a)

**Comment by josdemmers** [comment]
The `D4Companion.Updater.exe` is not supposed to be run directly. `D4Companion.exe` will use it to download and update new versions when available.

But I will change this so that `D4Companion.Updater.exe` will start `D4Companion.exe` when run directly. That is probably less confusing.

**Comment by Arborym** [comment]
Gotcha—yeah, my initial interpretation was that it was supposed to be manually run by the user. The documentation change should get rid of that confusion 👍

**Comment by josdemmers** [comment]
Fixed in v1.1.8.0
