### ISSUE TITLE
it's still crashing v1.1.8

### ISSUE THREAD

**Issue by ygorluiz** [josdemmers/Diablo4Companion#18]
it's still crashing and some affix are not detected.

[logging.log](https://github.com/josdemmers/Diablo4Companion/files/12091456/logging.log)

**Comment by josdemmers** [comment]
If you drop the file `logging.log` in the text box it will add it as attachment. Easier to read that way :)

> it's still crashing and some affix are not detected

**Comment by ygorluiz** [comment]
> If you drop the file `logging.log` in the text box it will add it as attachment. Easier to read that way :)
> 
> > it's still crashing and some affix are not detected

done!

**Comment by josdemmers** [comment]
> it's still crashing and some affix are not detected

Can you take screenshots of the debug view for an affix that does not work? It should show what part is not detected.

**Comment by ygorluiz** [comment]
> > it's still crashing and some affix are not detected
> 
> Can you take screenshots of the debug view for an affix that does not work? It should show what part is not detected.


I tried to take a screenshow but it has crashed 3 times

**Comment by ygorluiz** [comment]
![Captura de tela 2023-07-18 224226](https://github.com/josdemmers/Diablo4Companion/assets/3037941/b2002c5d-2531-46c4-8278-8cbd8e337a6a)

**Comment by josdemmers** [comment]
The debug view should show more info. See example below. But probably need to fix those crashes first.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/e60d8b2b-9129-4e84-9ce3-333cf21e5e8d)
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/3a82582d-999f-4c84-93d7-733255fb83c4)

**Comment by josdemmers** [comment]
Not sure what is going on with your system. There are multiple generic exceptions that don't tell me much. So will have to guess a bit.

1. `System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.`
2. `Emgu.CV.Util.CvException: OpenCV: Failed to allocate 30700416 bytes`
3. `System.OutOfMemoryException: Out of memory.`
4. `System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (0x88980406)`

The first one could be related to permission issues. From what location are you running the companion app?
The 2nd and 3rd could be related to lack of memory. How much memory does your PC have and much is left when Diablo is running as well?
The last one could indicate drivers that are out of date. For example your GPU driver.

**Comment by ygorluiz** [comment]
fixed in 1.1.9
