### ISSUE TITLE
Font scale issues

### ISSUE THREAD

**Issue by Nevodark** [josdemmers/Diablo4Companion#2]
When font size is set to large the words "Legendary X" such as "Legendary Amulet" or "Legendary Gloves" are split across 2 lines making it impossible to create a new resolution preset.

![image](https://github.com/josdemmers/Diablo4Companion/assets/5985558/ba384dfc-5ad7-4772-a0ba-267cda52d332)

**Comment by josdemmers** [comment]
Hey Nevodark that shouldn't be a problem. Multiple lines is supported as well.
You can also do this for affixes with multiple lines.

**Comment by josdemmers** [comment]
Multiline works now for item types, affixes, and aspects.
