### ISSUE TITLE
Overlay not appearing

### ISSUE THREAD

**Issue by rusagent** [josdemmers/Diablo4Companion#20]
I unpacked the latest release, configured it with a profile (item rarity doesn't stick when i select rare), downloaded the 1080p profile and set it. Then in-game i hovered over the button for the overlay. Then i hovered over any item just to see that no overlay is visible. Then i checked the debug tab to see but there wasn't anything either. Tried some different values at the slider to no avail.
Do i have to create a own config or should it work out of the box?

**Comment by rusagent** [comment]
Hey @josdemmers, thanks for the detailed answer.

so here are my settings:

dDiablo4Companion
![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/fcc51971-4af1-444b-b9ad-a042071ac71b)
![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/0ec87ee9-1569-44f7-bd0e-2f9f60dabc98)
![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/ae44b7fd-6859-4c0e-8e41-63a08daab61c)

D4
![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/de790794-bcbe-4e86-a179-7b3a505f94bb)


And this screenshot from d4 with the overlay activated: 

![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/938e2025-4bed-40a5-b0b5-2d86a0d7e468)

And here from the debug tab:

![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/73b3e7de-7ca9-4ddf-851c-1f1d101805e1)

When i click through the images in the debug tab only the Item Tooltip shows the image. The other ones don't show anything at all.

And here the config files

AffixPresets.json
`[
  {
    "Name": "drood",
    "ItemAffixes": [
      {
        "FileName": "cooldown reduction.png",
        "Type": "helm"
      },
      {
        "FileName": "maximum life.png",
        "Type": "helm"
      },
      {
        "FileName": "total armor.png",
        "Type": "helm"
      },
      {
        "FileName": "willpower.png",
        "Type": "helm"
      },
      {
        "FileName": "maximum life.png",
        "Type": "chest"
      },
      {
        "FileName": "physical damage.png",
        "Type": "chest"
      },
      {
        "FileName": "storm skill damage.png",
        "Type": "chest"
      },
      {
        "FileName": "rank of tornado.png",
        "Type": "gloves"
      },
      {
        "FileName": "attack speed.png",
        "Type": "gloves"
      },
      {
        "FileName": "critical strike chance.png",
        "Type": "gloves"
      },
      {
        "FileName": "willpower.png",
        "Type": "gloves"
      },
      {
        "FileName": "maximum life.png",
        "Type": "pants"
      },
      {
        "FileName": "damage reduction from distant enemies.png",
        "Type": "pants"
      },
      {
        "FileName": "damage reduction from close.png",
        "Type": "pants"
      },
      {
        "FileName": "willpower.png",
        "Type": "pants"
      },
      {
        "FileName": "movement speed.png",
        "Type": "boots"
      },
      {
        "FileName": "movement speed for.png",
        "Type": "boots"
      },
      {
        "FileName": "spirit cost reduction.png",
        "Type": "boots"
      },
      {
        "FileName": "willpower.png",
        "Type": "boots"
      },
      {
        "FileName": "spirit cost reduction.png",
        "Type": "amulet"
      },
      {
        "FileName": "cooldown reduction.png",
        "Type": "amulet"
      },
      {
        "FileName": "storm skill damage.png",
        "Type": "amulet"
      },
      {
        "FileName": "damage reduction from close.png",
        "Type": "amulet"
      },
      {
        "FileName": "spirit cost reduction.png",
        "Type": "ring"
      },
      {
        "FileName": "cooldown reduction.png",
        "Type": "ring"
      },
      {
        "FileName": "damage to close enemies.png",
        "Type": "ring"
      },
      {
        "FileName": "critical strike damage.png",
        "Type": "ring"
      },
      {
        "FileName": "vulnerable damage.png",
        "Type": "weapon"
      },
      {
        "FileName": "damage to close enemies.png",
        "Type": "weapon"
      },
      {
        "FileName": "core skill damage.png",
        "Type": "weapon"
      },
      {
        "FileName": "critical strike damage.png",
        "Type": "weapon"
      }
    ],
    "ItemAspects": [
      {
        "FileName": "stormchaser - tornado will seek up.png",
        "Type": "offhand"
      }
    ]
  }
]`

Settings.json

`{
  "DebugMode": false,
  "DevMode": false,
  "LiteMode": true,
  "SelectedAffixName": "drood",
  "SelectedSystemPreset": "1920x1080_SMF_en",
  "ThresholdMin": 57,
  "ThresholdMax": 255,
  "ThresholdSimilarityTooltip": 0.05,
  "ThresholdSimilarityType": 0.05,
  "ThresholdSimilarityAffixLocation": 0.05,
  "ThresholdSimilarityAffix": 0.05,
  "ThresholdSimilarityAspectLocation": 0.05,
  "ThresholdSimilarityAspect": 0.05,
  "TooltipWidth": 380
}`


Hope this helps

**Comment by josdemmers** [comment]
Your screenshots looks darker than the default settings, that is probably causing issues. The debug image for the Item Tooltip should show a red rectangle like this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/54c1fda9-3638-4a39-a5f4-104b39be1d03)

Could you replace the `tooltip_all.png` with your own? Then it will work with your game settings as well.
It's located in the `Tooltips` folder.

Easiest way to do this is to press `Shift+Windows+S`, then use the snipping tool to draw a rectangle around the tooltip image and save it in the `Tooltips` folder.

**Comment by rusagent** [comment]
Ok great, I simply upped the brightness in-game a bit and now it works. 

2 more things (should i open 2 new issues for this)?

Check this 
![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/648a85b8-6b3f-4ac9-a2fc-7c2920ee4eea)

- Damage Reduction from Distant Enemies doesn't seem to get detected.
- There's a affix for druids missing in the list. Don't remember rn but will tell you when I found it again.

**Comment by josdemmers** [comment]
> Damage Reduction from Distant Enemies doesn't seem to get detected.

Multi line affixes can be difficult. You could check the image in the Affixes folder to see if it needs improvements. Or maybe try to replace it with your own image.

> Ultimate Skill DMG on the weapon gets detected although I didn't put it in the affix list.

Probably found a match on `core skill damage` because it's very similar. You could try to create a new image for `core skill damage` that includes the % as well. Maybe that makes it unique enough to longer see `Ultimate Skill DMG` as a match.

> Critical Strike DMG with earth skill/ with Werewolf Skills etc. on the weapon get detected although they're not in the affix list.

That is unfortunately a limitation of the template matching I'm using. Everything that contains `Critical Strike DMG` will be detected.

> There's a affix for druids missing in the list. Damage while in Human Form on the Chest piece. Maybe also while in Bear/Werewolf form is missing

That one is easy to solve. You can add any missing affix in the Affixes folder yourself. The app will detect any new affixes you add. I'm also planning to add a checklist in a few weeks that will show any missing affixes.

**Comment by V4MPZZ** [comment]
out of curiosity , do we ad each type of preset for item , like glove 1 preset , weapon 1 preset of just 1 preset and seletc all that we wanted

**Comment by josdemmers** [comment]
Are you talking about this preset?
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/b613a2a6-4fb2-4eb6-80b5-8674e4209939)

A preset is for all item slots. For each preset you specify for all items slots the affixes you want.
