### ISSUE TITLE
Question about Blizzard Warning

### ISSUE THREAD

**Issue by billabonGS4** [josdemmers/Diablo4Companion#21]
Hello 
I just saw this report. Do you think this also applies to your software? Because that would mean you could get banned by using D4 Companion right now, right?
![blizzard](https://github.com/josdemmers/Diablo4Companion/assets/53131015/97f92a0e-a1fe-41ca-afcb-028e77551570)

**Comment by josdemmers** [comment]
Saw the message as well, have been discussing it on Discord. As this app only gives a small quality of life improvement we think it is safe to use and Blizzard will tolerate those kind of apps. But only time will tell.
Other Blizzard games with similar EULA have apps that are tolerated as well (such as for Heartstone).

The Diablo4Companion app only uses image recognition, there is no memory reading or other interaction with the game. That should make it relatively safe to use.

Blizzard will probably go after that apps that give unfair advantages, such as the mentioned TurboHUD4.

**Comment by josdemmers** [comment]
Almost time for season 2. Blizzard does not seem to have any problems with this app and it's safe to use.
Closing this issue.
