### ISSUE TITLE
missing affices

### ISSUE THREAD

**Issue by Zaptear** [josdemmers/Diablo4Companion#23]
trying to put together a barb build here and it seems there is a lot of missing affixes like life on kill  ranks of death blow stuff like that is there a way we can add to the list of affixes?

**Comment by josdemmers** [comment]
Yes everyone can add missing affixes. In the app folder you have an Affixes folder containing all current affixes. 
To add new affixes add an image for the missing affix. 
Easiest way to do this is by using `Shift+Windows+S` to open the snipping tool and capture/save the missing affix.
You can either find them yourself ingame or inspect other players ingame.

If you share the missing affixes afterwards with me I can add them for everyone.

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/0fccc128-cf3b-4379-9d84-8783c7377d0e)

**Comment by Zaptear** [comment]
that worked thanks
