### ISSUE TITLE
Font Scale

### ISSUE THREAD

**Issue by smoochy** [josdemmers/Diablo4Companion#28]
Hi,
thank you very much for this useful tool. Really helps and minimizes the time needed to spend in town identifying the 99% of cracp loot.

One question though:

I normally play with the font scale ingame set to small. I noticed that D4C is not working with the 1440p preset, as it requires font scale set to medium.

Would it mean, that I would need to recreate every .png file for affixes, aspects etc so it would work with small font scale?

Wouldn't it be possible for you to handle this internally? You provide an option where the user sets its font scale. There is no need to create new .png files. The ones provided have 100%, which means medium. If the user set another font scale you take the images and scale them down or up, depending if small or large font scale is set ingame.

Cheers, 
smoo

**Comment by josdemmers** [comment]
Tried scaling in the past for different resolutions but that did not work good enough. Too many failed to match.
Maybe it works for the same resolution but different font sizes. But it can never work for all affixes.
The problem is when you change the font size between small, medium, large, the length of the affix text changes. So for one font size it fits on 1-2 line(s) while for the larger font it needs 2-3 lines.

**Comment by smoochy** [comment]
Mhh, bummer. I was thinking, that maybe, you could "train" your internal recognition with sample files. So for each resolution, you only need to take 3 screenshots (each for each font scale) instead of dozens of screenshots for each affix. For instance. Maybe take an affix, which has a line feed with medium font, no line feed with small and 2 line feeds with large font? 

I only know a little bit of Python, so I do have ideas, but don't know how to put this into working code.

In addition, would it be possible to get all possible affixes for each item slot extracted from the game files? Or at least have them in some list or so?

Would it be possible to have all affixes in a text file. For each affix you internally create a png file for the needed font scale and your image recognition ingame is based on that? That would take of a huge amount of work from the end user.

**Comment by josdemmers** [comment]
> Mhh, bummer. I was thinking, that maybe, you could "train" your internal recognition with sample files. So for each resolution, you only need to take 3 screenshots (each for each font scale) instead of dozens of screenshots for each affix. For instance. Maybe take an affix, which has a line feed with medium font, no line feed with small and 2 line feeds with large font?

No that doesn't work like that. The app somehow needs to know which affix it is. The closes implemention that matches this will be by using OCR.

> In addition, would it be possible to get all possible affixes for each item slot extracted from the game files? Or at least have them in some list or so?

Yes that is possible. Working on that already. But not sure when that will be ready.

> Would it be possible to have all affixes in a text file. For each affix you internally create a png file for the needed font scale and your image recognition ingame is based on that? That would take of a huge amount of work from the end user.

The app uses template matching. The images have to be a close enough match to work. It might be possible if you can generate a good enough match. Other issue would be all the different single and multi-line affixes depending on font size and screen resolution. You would need to match that exactly as well.

Thanks for the ideas thought!
