### ISSUE TITLE
languages

### ISSUE THREAD

**Issue by shanduoduo** [josdemmers/Diablo4Companion#3]
Can other languages ​​be recognized?

**Comment by josdemmers** [comment]
Yes will work for all languages. You will however need to create your own system preset.
That is needed to match your resolution and language.
See the wiki on how to get started:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

You can share your system preset afterwards with me so others can use it as well.

**Comment by shanduoduo** [comment]
Does it support 4k resolution? i failed the test

**Comment by josdemmers** [comment]
The default images are for 2560x1440 only. But if you create your own for 4k it should work.
I don't have a 4K monitor myself so can't really help you with this one.

I would suggest to start with these three images:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/337489e3-ce9f-4281-bad2-182ddb27a357)
And then open the debug view and verify if you see the red outline.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/a5581320-1b33-4fde-8d1d-7f77c49f6de3)

When you have to that working you can continue with the other images

**Comment by shanduoduo** [comment]
<img width="1032" alt="image" src="https://github.com/josdemmers/Diablo4Companion/assets/52020098/ce5f97ef-5609-4f91-aa57-8e5573787536">
I can't see anything in this interface

**Comment by josdemmers** [comment]
You need to enable the overlay first, looks like it's still paused.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/3df430d6-ce09-41b7-8156-b154e7084a88)

**Comment by shanduoduo** [comment]
<img width="158" alt="image" src="https://github.com/josdemmers/Diablo4Companion/assets/52020098/cf3c571a-420e-46e0-b22b-e02423263536">
The device can be identified, but the range in the red frame seems to be wrong. .

**Comment by josdemmers** [comment]
That is too bad. I'll need to fix that first.
When a new version is ready I'll let you know.
Maybe this evening but probably tomorrow.

**Comment by shanduoduo** [comment]
<img width="398" alt="image" src="https://github.com/josdemmers/Diablo4Companion/assets/52020098/a54f8c97-6991-410d-8e34-3f1d74c46dac">
A bug, I try to test and identify an entry, it will show red and green at the same time, and it is very slow

**Comment by shanduoduo** [comment]
<img width="373" alt="image" src="https://github.com/josdemmers/Diablo4Companion/assets/52020098/7a5d6ae6-ceb8-4ce2-a442-98346b3fb701">
It takes about 1~2 seconds for the time marker to appear or disappear

**Comment by josdemmers** [comment]
Ok good, you got it working with another resolution.

Regarding the bugs. The app works by comparing images to find the best match. This is not very fast unfortunately. But I'm still working on improving this.

The red/green overlap could happen when two affixes look similar.

**Comment by shanduoduo** [comment]
Hi,josdemmers
I can't open the program today after adding the affixes

**Comment by shanduoduo** [comment]
Oh, I see, a png I tested before was deleted by me, and the config remembered the non-existing png, so it couldn’t be opened

**Comment by shanduoduo** [comment]
1.Gear Affix Presets will not record the last selection
2. After opening Affix Overlay, there is a chance that the system will blue screen of death and restart

**Comment by josdemmers** [comment]
> Oh, I see, a png I tested before was deleted by me, and the config remembered the non-existing png, so it couldn’t be opened

Will add a check for that.

> 1.Gear Affix Presets will not record the last selection 2. After opening Affix Overlay, there is a chance that the system will blue screen of death and restart

1. Not sure what you mean by this?
2. Never had any issues like this. Any extra info in the log file?

**Comment by josdemmers** [comment]
Release v1.1.0.0 is now ready, let me know if this solves your issue.

The wiki on how to create your own system preset is also updated:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

**Comment by josdemmers** [comment]
There is now a download manager available for the system presets. If you have a working Chinese preset you can send it to me and I'll add it to the download manager.

**Comment by shanduoduo** [comment]
Ok, so far I only have one class preset

**Comment by josdemmers** [comment]
No problem, that will already make it easier for others to get started.
Could you follow this naming format?
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset#naming-convention

Will need to following information to describe your configuration:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/f0775382-90aa-43b2-81a7-dbfdcbcbc5fa)

- Resolution
- HDR setting, is this on or off?
- Font: small, medium, or large
- Language: Chinese (Simplified) zh-CN? or Chinese (Traditional) zh-CHT?

Let me know if you have any questions.

**Comment by josdemmers** [comment]
Closing this issue. When you are ready to share your system preset let me know.
