### ISSUE TITLE
Button to scan all items ?

### ISSUE THREAD

**Issue by rhbrolo** [josdemmers/Diablo4Companion#30]
Hello @josdemmers , is it possible to scan all inventory or does it only work when you hover over an item and it's tooltip is shown ? Thank you

**Comment by josdemmers** [comment]
It only works when the tooltip is visible.

**Comment by rusagent** [comment]
Can the mouse maybe been automatically moved over the items and checked if there are 3-4 affixes that match, if not the mark the item as junk?

**Comment by josdemmers** [comment]
> Can the mouse maybe been automatically moved over the items and checked if there are 3-4 affixes that match, if not the mark the item as junk?

I have no plans to automate anything.

**Comment by rusagent** [comment]
Seems legit^^
