### ISSUE TITLE
Multiple Gear Affix Presets at the same time

### ISSUE THREAD

**Issue by smoochy** [josdemmers/Diablo4Companion#31]
Hi,

would it be possible to have multiple gear affix presets being active at the same time?
Currently I am playing a Stormclaw Druid build. And ofc I want to identify gear upgrades for that build easily.
But at the same time, I want to start collecting gear for another build, which needs different affixes.
So when only having one gear affix active, I could miss an item of the other preset.

A way to accomplish this could be, that each preset has a number attached. And this number is displayed at the green bubbles. So I easily could spot if that item is helpful for build 1 or build 2.

Cheers

**Comment by josdemmers** [comment]
The more you add the slower the app will become.
For now I would suggest to use the new hotkeys I added in the previous version to quickly switch between affix presets.

Maybe I can look into this further when I have a new GUI for the affixes.

> A way to accomplish this could be, that each preset has a number attached. And this number is displayed at the green bubbles. So I easily could spot if that item is helpful for build 1 or build 2.

That will probably be used in the future to show the difference in priority between affixes.

**Comment by smoochy** [comment]
> For now I would suggest to use the new hotkeys I added in the previous version to quickly switch between affix presets.

Thanks, will use this as a "workaround".
