### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by dkir2021** [josdemmers/Diablo4Companion#33]
Currently the scan seems to only happen when mouse is moved, it would be good to have this also happen when using a controller.

**Comment by josdemmers** [comment]
> Currently the scan seems to only happen when mouse is moved, it would be good to have this also happen when using a controller.

Controller should work fine as well. Others have been using it.
But you might need to add an extra tooltip image.

- `.\Tooltips\tooltip_all.png"`

This one looks for the Shift key image. You will have to check in-game how that looks like when you have a controller connected.

> as a note how do you want feature requests submitting? as I would like to be able to prioritise the affixes, with numbers 1,2,3 etc that could show with the colour circle. Their is also a python OCR https://github.com/mxtsdev/d4-item-tooltip-ocr that would allow you to get the affixes and you could even give % of perfection on the affixes.

You can use GitHub for that as well, just like this one for `controller support`. A separate GitHub issue for each feature request  works best.

Regarding OCR, no plans for that yet any time soon. But it is something I want to look into.
However not sure if it will be fast enough to give realtime information for the overlay.

**Comment by josdemmers** [comment]
Regarding the controller, you probably need to add an image to the tooltip folder similar to this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/0eb777b1-7461-416a-beb4-e9de09e3d55a)
