### ISSUE TITLE
Indicators not showing up when Occultist window open

### ISSUE THREAD

**Issue by smoochy** [josdemmers/Diablo4Companion#35]
The green / red indicators are not showing up, as soon as the Occultist trading window is opened. No matter which tab is selected.

When the Occultist window is closed, it works again.

**Comment by Commander-HK47** [comment]
Its most likely the following issue.

Likely you are only using the only the "shift" tool-tip reference image in your Images profile's "tooltips" folder to tell the program what to look for when looking for the tool-tip window. The Occultist doesn't allow for the shift commands, so they aren't rendered on the tool-tip panel.

If you want the application to show filtering dots while in the Occultist window, you will need to also include a image of the "Select"  command image in your profile's image/tooltips folder.

**Comment by smoochy** [comment]
Thanks, this did the trick.

Same goes for jeweler.
