### ISSUE TITLE
Configurable Affixes?

### ISSUE THREAD

**Issue by Gushus** [josdemmers/Diablo4Companion#39]
Is there a file where one can configure which affixes can be selected? - Would be cool to do so, because some of the affixes seem to be missing.

**Comment by josdemmers** [comment]
The available affixes are directly linked to the images you have in your system preset.
For example: `.\images\2560x1440_SMF_en\Affixes\`.

You can add any missing affixes yourself by taking screenshots and adding them to that folder.
If you send them to me afterwards I can share them with everyone.

I have plans for a new interface to better show which affixes are available but that is still a work in progress.

**Comment by Gushus** [comment]
Ou okay, thank you!

I thought you'd do this via OCR on a screenshot - but thanks for the info! :)

**Comment by josdemmers** [comment]
Probably later, if it's fast enough to give real-time info for the overlay.
Started with image recognition so I could support all 12 languages of Diablo. Without having to train OCR for different languages.
