### ISSUE TITLE
How to report missing affixes?

### ISSUE THREAD

**Issue by JackD111** [josdemmers/Diablo4Companion#4]
Hey, nice work but I noticed that class specific affixes are missing. 

This is a list of affixes missing for bone spear necro build:

+X to Bone Spear
Maximum Essence
5. Lucky Hit: Up to 5% Chance to Restore Primary Resource
6. Lucky Hit: Up to % Chance to Slow
Essence Cost Reduction
+xx Ranks to Corpse Tendrils
+xx Ranks to Evulsion
 Critical Strike Damage with Bone Skills

One general one:

% Total Armor

How do we report affixes so you can implement them?

**Comment by josdemmers** [comment]
Hey Jack you can add them yourself for now.
Maybe I can add something next weekend to make sharing affixes between users easier.

All you need to do to add an affix is to drop it in the affixes folder.
Easiest way to do this is by pressing `Shift+Windows+S` (this opens the snipping tool), then capture your affix and save it.

**Comment by josdemmers** [comment]
Presets for 1080p and 1440p are now added to the download manager with additional affixes.
If you notice some missing ones you can create them yourself. Also don't hesitate to zip them all together and send them to me. That way everyone can use them.

**Comment by Delvint** [comment]
Hey Jos!
I would love to send you some image files, but I cannot find an email address or something similar.

**Comment by josdemmers** [comment]
> Hey Jos! I would love to send you some image files, but I cannot find an email address or something similar.

You can use the GitHub issues and add them as attachment. There is also a Discord you can join and share them there:
https://github.com/josdemmers/Diablo4Companion#the-hidden-gaming-lair
