### ISSUE TITLE
Druid Totem Affixes not recognized

### ISSUE THREAD

**Issue by rusagent** [josdemmers/Diablo4Companion#40]
Hey man,

as you can see here 

![image](https://github.com/josdemmers/Diablo4Companion/assets/1582815/cc6cba38-e4e4-4386-8b90-cd15a869bdf3)

the affixes for druid totems are not getting recognized. Any idea why?

**Comment by josdemmers** [comment]
There was a bug in the previous versions which is now fixed. When `Lite Mode` is active all items with `Damage per second` are seen as weapon. This includes the totem as well.

If you want to have different affixes for your weapons and totem you need to disable the `Lite Mode`.

In the previous versions the Totem was not excluded causing it to sometimes use the weapon affixes and other times the totem affixes.

**Comment by rusagent** [comment]
Alright - when i disable the lite mode then the affixes for the totem get detected. But the affixes for 2 and 1 hand Axes and Maces won't get detected anymore. Only Staffs :/

**Comment by josdemmers** [comment]
That's why `Lite Mode` is very easy. You only need the `damage per second` image.
When you turn that off you need an image for each item type.

Check the `Types` folder for the axes and maces images. You might need to add them yourself.

**Comment by rusagent** [comment]
I added the images and now it gets detected (=
