### ISSUE TITLE
Having trouble getting variable affixes to work correctly

### ISSUE THREAD

**Issue by SQyP2h7ykGZLzwrVaofA** [josdemmers/Diablo4Companion#42]
One of the preferred affixes for a couple of my items is:

Lucky Hit: Up to a 5% Chance to
Restore +XX% Primary Resource
[YY.Y - ZZ.Z]%

XX, YY and ZZ are variable.

It shows up as 3 lines on my screen resolution/font size.

Using a rectangular clip of from one of my items, of the complete 3 line text, D4 Companion has no trouble recognizing it as a "green dot" affix on that item. On another item with the same affix, but different values for XX, YY and ZZ, however it shows up as a "red dot" affix.

I've tried just using the first two lines, but that still doesn't work, implying that it's the XX% that's causing the image comparison to fail.

I've tried just using "Primary Resource", but that causes both items to display the red dot.

I've also tried adjusting the Affix Similarity Threshold up and down, with the highest and lowest value still failing.

The two items are a focus and a pair of gloves, if that makes a difference.

My screen resolution is 3440X1440, Medium Font, non-HDR.

Is it possible to use a non-rectangular clipping region, to omit the XX part from the clip?

Is there another way to make this work the way I want it to, without creating a clip with every conceivable percentage for XX and making each clip active for the items with this desired affix?

The "Heal" version of this affix is identical in format, with "Heal" replacing "Restore" as the first word on the second line, meaning I can't just clip the first line and use it.

Thanks for a neat time-saving helper!

**Comment by rusagent** [comment]
This can maybe help you https://github.com/josdemmers/Diablo4Companion/issues/20#issuecomment-1650417812

**Comment by josdemmers** [comment]
Multiline affixes can be difficult. Depending on the values of XX, YY the lines can even look different between items.
See damage reduction from close as example:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/c6989e58-b880-4bc5-9872-3323fe54cb50)

In your case I would try something like below. Hopefully that is unique enough to work.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/9519efda-a5da-4b7c-8099-5d578100a99e)

**Comment by SQyP2h7ykGZLzwrVaofA** [comment]
Changing the image to what you suggested did the trick. Thanks so much!
