### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by senic35** [josdemmers/Diablo4Companion#46]
Might be worth to work together with the guys over at https://github.com/inn3rvoice/inventory_alpha

Has some very similar features, as well as a database of scanned items for trading and/or reference.

(I'm not affiliated in any way, I just like both projects)

**Comment by josdemmers** [comment]
Hi @senic35 thanks for your interest. I have seen Diablo QOL before, looks good. But I prefer to keep both projects separated.
