### ISSUE TITLE
Some affixes missing

### ISSUE THREAD

**Issue by gianluahorrocks** [josdemmers/Diablo4Companion#49]
Hi, I don't know if they just haven't been implemented yet, but I noticed some affixes are missing and not available as choices to search on tooltips. For example, on my twisting blades Rogue, there's no option to search for "Ranks of shadow imbuement", "Energy cost reduction", or "Ranks of the Weapon Mastery passive"

**Comment by josdemmers** [comment]
Hi @gianluahorrocks it differs per system preset what affixes are missing. Some presets are updated more frequently than others.
But it's easy to add any missing affixes yourself. There is a guide available here:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-add-affixes-to-an-existing-System-Preset

**Comment by gianluahorrocks** [comment]
Ohhh okay thats great, I was tryna figure out how to add them myself. Thanks very much.
