### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by Mouchoir** [josdemmers/Diablo4Companion#5]
Hello,

I am trying your tool as we speak, and I think it can be very helpful !
While using it, I had a few ideas on how it could be improved:

- Allow to prioritize the affixes (dragging & dropping them as a list) and display the priority in the overlay

![image](https://github.com/josdemmers/Diablo4Companion/assets/4174327/ec39dad6-d13b-4d58-8755-d2acda2b2ab3)
![image](https://github.com/josdemmers/Diablo4Companion/assets/4174327/2e7a7323-86c0-4560-b720-2c024d1ed6f5)

- provide us with a link where we can send our own screenshots so you can add them to the next release
- replace the "_" with spaces when you research : I am guessing the search is based on the screenshot name. If I have "all_stats.png", it would be nice to be able to search "all stats"
- I'm unsure why there is two image folders but if possible, merge the normal and light image folders
- Maybe a disclaimer should be added to the README if there is any risk using the tool ? I know Blizz isn't too nice with 3rd party softwares

Thanks again for this tool !

**Comment by josdemmers** [comment]
Your welcome, glad you like it. Thanks for all the suggestions! First going to work on getting the basic features more stable. Detection of tooltips/affixes is still off sometimes, giving weird results.

- Prioritize the affixes 
Was planning to this by introducing different colors per priority. That works for you as well?
- Sharing images
Planning a downloader directly in the app to get system presets for different resolutions. No idea yet how to upload them.
- Affix filter
Yes I notices that _ as well while playing yesterday, was annoying. You can remove them from affixes and aspects without problems. The other images will need them to work correctly.
- Lite mode
To make it more obvious the different mode is selected. But maybe I'll just merge them and add a toggle button on the GUI to let the user switch between `Lite` and `Normal` mode.
- Disclaimer
Yes I should add that. But fyi, don't expect much risk here. Everything is done using image recognition, there is no interaction with the game.

**Comment by Mouchoir** [comment]
Thanks for your answers !

Having different colors can indeed help prioritize the different affixes. A list seemed easier to me, but whatever is simpler for you to implement !

In my opinion, the tool will be even easier to use for new users if all affixes are embedded when you download the companion. As a rogue, I had a few ones I needed (I can see you're playing a sorceress) and I thought that instead of having everyone screenshot their affixes, there should be a way for me to send the ones I've already screenshotted so you can add them to the next release. Hopefully, all users will start sharing theirs and the tool will have every possible affix.

I also have a question : how does it handle the value of the aspects ? 
For example, if I have a screenshot that comes with a value, will it match the same aspect but with another value ?
![image](https://github.com/josdemmers/Diablo4Companion/assets/4174327/d77e1636-c20c-4f1c-8556-9e9b0b372c25)

If it could match a certain % of a screenshot, then it would recognize an aspect even with a different value or range from the reference screenshot
![image](https://github.com/josdemmers/Diablo4Companion/assets/4174327/8c3277a3-d1d9-4134-8c80-ae3fd9c92662)

Another suggestion : having the tool automatically check for updates :)

**Comment by josdemmers** [comment]
> Having different colors can indeed help prioritize the different affixes. A list seemed easier to me, but whatever is simpler for you to implement !

Will see what works best, maybe a combination. Idea is also to have groups instead of a single priority for each affix.

> In my opinion, the tool will be even easier to use for new users if all affixes are embedded when you download the companion. Hopefully, all users will start sharing theirs and the tool will have every possible affix.

Will add it to the readme later for users to send those images. First need to create something for users to easily download new presets.
 
> I also have a question : how does it handle the value of the aspects ? 

Images only for now, so no support for variable numbers. This will however be possible after I have replaced the images with OCR. Idea is to first have a stable version using images. Then everyone can use that while I work on OCR.

> Another suggestion : having the tool automatically check for updates :)

Already tested that in my other project for New World. So I'll add that for sure later.

**Comment by ygorluiz** [comment]
@josdemmers `   Emgu.CV.Util.CvException: OpenCV: Failed to allocate 4015872 bytes
   at Emgu.CV.CvInvoke.cveMatchTemplate(IntPtr image, IntPtr templ, IntPtr result, TemplateMatchingType method, IntPtr mask)
   at Emgu.CV.CvInvoke.MatchTemplate(IInputArray image, IInputArray templ, IOutputArray result, TemplateMatchingType method, IInputArray mask)
   at D4Companion.Services.ScreenProcessHandler.FindItemType(Image`2 currentTooltip, String currentItemType)
2023-07-18 22:42:25.5920|ERROR|D4Companion.Services.ScreenProcessHandler|FindItemType    `

it's still crashing

**Comment by josdemmers** [comment]
@ygorluiz Could you create your own issue for this and upload the complete log file. (`.\Diablo4Companion\Logging\`)
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/76c67402-4d0a-4d7b-a96a-205cbfb943fb)

**Comment by V4MPZZ** [comment]
can we get a sperate tab for just aspect ? instead of it link to and item ? maybe like we can select a few aspect in 1 slot

**Comment by josdemmers** [comment]
> can we get a sperate tab for just aspect ? instead of it link to and item ? maybe like we can select a few aspect in 1 slot

Please create a new issue for feature requests. Makes it easier for me to keep track of them.
But yes that is possible. I'm planning to make a new GUI for this, can still take a few weeks before it's ready.

**Comment by josdemmers** [comment]
Thanks for the suggestions, all included now except the priority.
First going to work on a new GUI to manage affixes.
