### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by SQyP2h7ykGZLzwrVaofA** [josdemmers/Diablo4Companion#51]
I had been using 1.14 without any problems, then upgraded to 1.15 and then 1.16 without playing Diablo. Started up Diablo again and DIablo Compnaion doesn't seem to work any more.

It doesn't put the green or red dots on my tooltips any more.

It runs, but can't seem to find the tooltips on the screen. It also sometimes doesn't seem to be able to capture the screen, or at least it doesn't update the capture shown in the window looking at the debug screen.

For example, it will show my character with my inventory open, but when I mouse over an item and the tooltip pops up, Diablo Companion still shows just my character's inventory, with no tooltip open. This is viewing Diablo Companion's debug menu.

FInally, when it does seem to attempt to look for a tooltip, it displays a rectangle on the debug menu that consists of the right third or half of my character pane, when the tooltip is to the left of my character.

I'm running 3440 X 1440, medium font, non-Hdr, on Windows 10, using images I've snipped myself, that used to work with older versions of the program.

This latest version also couldn't find my screen images directory until I stuck a "p" in my existing directory name. I only added it because I noticed that the predefined resolutions had a "p" in them. Nothing on the roll your own resolution wiki mentions that, nor any other required changes to the stuff in the Images directory.

Thanks in advance!

**Comment by josdemmers** [comment]
Thanks for the reminder. Just updated the readme and wiki text (will do the images tomorrow). The names of the system presets were changed a few days ago with the v1.1.16 release.
Making some significant changes in preparation for the 2.0 release. Will update the wiki with more info when that is ready.

Renaming your system preset to `1440p_SMF_en` or downloading the latest `1440p_SMF_en.zip` from the download manager should fix everything. Each preset works for both normal and widescreen resolutions. e.g. 2560x1440 and 3440x1440 now both use the 1440p preset.

> Finally, when it does seem to attempt to look for a tooltip, it displays a rectangle on the debug menu that consists of the right third or half of my character pane, when the tooltip is to the left of my character.

This was changed in v1.1.14, the capture area now uses your current mouse position so it doesn't need to scan your whole screen.

> This latest version also couldn't find my screen images directory until I stuck a "p" in my existing directory name. I only added it because I noticed that the predefined resolutions had a "p" in them. Nothing on the roll your own resolution wiki mentions that, nor any other required changes to the stuff in the Images directory.

The readme and wiki text are now updated, will update the images tomorrow.

Could you try again and post the images from the debug menu if it's not working.

**Comment by josdemmers** [comment]
Closing this as v2.0 is now available.
