### ISSUE TITLE
[Suggestion] Option for Items with 800+ Item Power Only

### ISSUE THREAD

**Issue by meeks726** [josdemmers/Diablo4Companion#53]
I think it would be great to have an option to only scan items with Item Power of 800 or greater. So if an item is less than 800 Item Power then don't do scan for any affixes etc

**Comment by imm0r** [comment]
Absolutly i have thought about requesting this too but then moved my request until v2 will hit the light ;)

**Comment by imm0r** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/7317860/104093fb-ab9a-4a57-8191-363b18c679d3)

searching for this should pretty much do the job... only difficulty should be to get the correct position to look for the image for every possible resolutionl.

**Comment by josdemmers** [comment]
Idea is good, now we need a reliable way to implement it.
Upgrading items changes the location as well, see examples below. Also just the 8 wont be enough. There is an 8 in 800, 80, and 8 as well.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/b6a20176-d330-48e7-b609-7c6f336f457a)
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/829374a9-f9cb-4123-a722-c0a033a43bed)

**Comment by meeks726** [comment]
I think in this case and only specially for this part of the check, converting the 'Item Power' section in the tooltip into a string might be helpful and have a statement to check if the string value is greater than 800. But then again, this points back to what you said about converting to strings in the other thread about having multiple languages etc

**Comment by meeks726** [comment]
Could maybe do the same checks as finding the affix locations by using an image of the "Item Power" without the number

**Comment by josdemmers** [comment]
Now that the app uses OCR is was easier to implement.
Item power filter will be available in the v3.2.0.0 release.
