### ISSUE TITLE
Missing Rank of blood lance 1440p_SMF_en

### ISSUE THREAD

**Issue by mipsou** [josdemmers/Diablo4Companion#59]
Missing Rank of Blood Lance
![image](https://github.com/josdemmers/Diablo4Companion/assets/5244347/74a21f43-dfb9-43eb-8b22-ce527c7d30a4)

![image](https://github.com/josdemmers/Diablo4Companion/assets/5244347/811334da-798f-4b36-a5f0-a435245c53d9)

**Comment by josdemmers** [comment]
Is this for the `1440p_SMF_en` system preset?

Most necro affixes/aspects are missing. Haven't played that class yet.
But everyone can contribute to complete the list. Just keep sending them and I'll add them.
You can also collect a few more and send them as zip file.

**Comment by mipsou** [comment]
YeS, i use 1440p

**Comment by josdemmers** [comment]
Added affix
