### ISSUE TITLE
Overlay not popping up

### ISSUE THREAD

**Issue by senic35** [josdemmers/Diablo4Companion#6]
What exactly am I missing here?

![image](https://github.com/josdemmers/Diablo4Companion/assets/18623619/b847311d-0152-43ae-b4f7-646eda7fb2ca)
![image](https://github.com/josdemmers/Diablo4Companion/assets/18623619/6fbc74d7-8a5d-4e38-a55d-f549cd091a39)

I had it work once the other day, but now it doesn't. Shows up in the debugger but nothing in the actual overlay.
My resolution is 1080p but it still worked with the 1440-lite mode before.

**Comment by josdemmers** [comment]
Currently rewriting the tooltip detection. Next version should work better and be more precise. Might be ready tomorrow.
But the 1080p vs 1440p is never going to work 100%. You will really need better matching images.

There is a guide here to get started. But I recommended to wait until the next version. I'll need to update the wiki to match the next version. Will let you know when it's ready.
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

**Comment by senic35** [comment]
I'm currently fooling around with your newest build release 1.1.0.0 and started adding my own 1080p config, as well as some images I need. But right now the debug window looks very offset and the detection only works for one specific chestplate in my inventory. Any idea why this might be?

![image](https://github.com/josdemmers/Diablo4Companion/assets/18623619/9982359d-98c3-4e26-8581-7219d32d1e93)
![image](https://github.com/josdemmers/Diablo4Companion/assets/18623619/caa64086-34d9-4a1a-aa8a-50e4ca010317)

**Comment by josdemmers** [comment]
Nice work, feel free to share your system preset when you get it working.
I just updated the wiki a few minutes ago, should explain everything to get that working.
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

See this section to get the correct tooltip width:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

**Comment by josdemmers** [comment]
@senic35 With the v1.1.2.0 release there is now a preset for 1080p. You can use that as a starting point.
You can download it from the download manager in settings.

**Comment by rusagent** [comment]
not popping up for me at all :/ i've got 2 monitors - is it because of that?

**Comment by josdemmers** [comment]
@rusagent Feel free to create a new issue next time instead of using an old closed one.

> not popping up for me at all :/ i've got 2 monitors - is it because of that?

No not at all. Using 2 monitors is even better, makes is much easier to set everything up correctly.
I suggest to open the debug view and check which part is not working for you.
