### ISSUE TITLE
Movement Speed also shows for "After killing elites"

### ISSUE THREAD

**Issue by aden3431** [josdemmers/Diablo4Companion#68]
When selecting "% Movement Speed" it seems to also give a green dot next to "% Movement Speed after killing an elite"

**Comment by aden3431** [comment]
This seems to be with anything that has more writing after.

Had another affix for "% damage reduction" also show for "% damage reduction from poisoned enemies"

**Comment by josdemmers** [comment]
Updated wiki with example.
