### ISSUE TITLE
Some user experience

### ISSUE THREAD

**Issue by EFHT** [josdemmers/Diablo4Companion#7]
Firstly, I am not an English-speaking user, and my window ratio is relatively unusual (3456x1200), so my issue may not be common for everyone.

When I am using it, only equipped items can be recognized, which is very strange. I don't know where the problem is coming from.

Regarding the recognition of affixes and dot-affixes_X, I have tried cropping the image myself to achieve better recognition results. For users who cannot use the presets, it is not a good experience to replace them one by one. Perhaps you could add a tab in the DEBUG interface for re-capturing existing affixes? For example: 1. Select the affix. 2. Click the replace button, and the program starts monitoring clipboard events. 3. The user manually takes a screenshot. 4. The program pops up a preview and a prompt asking whether to replace it.

These are my user experiences, and I hope they are useful to you. Thank you for sharing your ideas.

**Comment by josdemmers** [comment]
Thanks for your feedback. The next update will make it easier to get it working for different resolutions. That will most likely fix your issue with equipped items as well.
But I have to solve some crashes first before I can release it.

> Perhaps you could add a tab in the DEBUG interface for re-capturing existing affixes?

Windows has a build in feature that works easy enough I think.
If you press `Shift + Windows + S` the snipping tool will open which allows you to draw a rectangle around the affix and save it.

I have also plans to add a download manage in the app to directly download system presets for each resolution created by the community.

**Comment by EFHT** [comment]
Glad to receive your reply.
I know that Windows has a built-in screenshot function, and in fact, that's what I use to take screenshots. I'm also happy to see that you support users replacing local files to make them more localized and customizable. However, as you know, there are dozens to hundreds of different affixes in D4, and replacing them one by one with screenshots is not a very enjoyable preparation work. Additionally, I'm not sure if different file formats, such as PNG and JPEG, would affect recognition efficiency.

**Comment by josdemmers** [comment]
> However, as you know, there are dozens to hundreds of different affixes in D4, and replacing them one by one with screenshots is not a very enjoyable preparation work. 

Indeed, combining the different item types and affixes you would need hundreds of images. Luckily this is only the first version of the app. It now uses images so everyone can expand it themselves with the affixes they like. Also it supports all languages without any effort.
When this version is stable enough with some basic features I'll start working on a version 2 which uses OCR.

Then you'll only need a few images to detect the tooltip and the remaining part will be converted from image to text.

**Comment by EFHT** [comment]
I'm glad there will be future versions. I'm a bit eager for them. Thank you for your hard work. I don't have any more questions. Have a great day!
