### ISSUE TITLE
Controller Support not working with Xbox controller

### ISSUE THREAD

**Issue by KyleDeschene** [josdemmers/Diablo4Companion#72]
Hover function does not work when using controller. Works as expected when mouse is used. 

OS: Win 10 Pro
Controller: Xbox controller using wireless adapter (non-blutooth)

**Comment by notsonata** [comment]
same here, using ps4 controller

**Comment by josdemmers** [comment]
With the current version it still requires some manual actions after turning on `Controller Mode`.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/4f2a9a8d-b7bf-4698-a394-8c797fa58331)

Steps:
- Copy the controller icon from `.\Diablo4Companion\Images\1440p_SMF_en\Tooltips\Optional\`
- Paste it in `.\Diablo4Companion\Images\1440p_SMF_en\Tooltips\`

If the icon for your controller is missing send it to me and I'll add it in the next release.

I'm planning to automate this process in the next release. Then the only thing you need to do is enabling `Controller Mode`.

**Comment by KyleDeschene** [comment]
Ok Perfect, the image is definitely missing for Xbox. What method/ preferred way of grabbing the image do you require.

**Comment by josdemmers** [comment]
The easiest way is to use the windows snipping tool. `Shift+Windows+S` and capture the controller button that you need.
You will have to test which button works best for xbox by checking which button is always visible on the item tooltip.

**Comment by KyleDeschene** [comment]
![Xbox_Button](https://github.com/josdemmers/Diablo4Companion/assets/11459938/9b6feac4-f36b-41b8-8290-15e4d0ca6105)

Attached is what i just generated, let me know if this suffices.

**Comment by josdemmers** [comment]
I cut out the part I needed. Could you test if this works for you?
![tooltip_controller_x](https://github.com/josdemmers/Diablo4Companion/assets/8627157/0650c304-2d1e-40bd-8a42-e0eff80bc71f)

Also is this for `1440p_SMF_en`? or for another resolution?

**Comment by notsonata** [comment]
i did as you instructed and it works now. thank you! i tried it on 1080p resolution

**Comment by KyleDeschene** [comment]
> I cut out the part I needed. Could you test if this works for you? ![tooltip_controller_x](https://user-images.githubusercontent.com/8627157/284140009-0650c304-2d1e-40bd-8a42-e0eff80bc71f.png)
> 
> Also is this for `1440p_SMF_en`? or for another resolution?

sure I can test it out, yes this is for 1440p_SMF

**Comment by josdemmers** [comment]
Fixed in Release v2.3.0.0, see wiki for more info.
https://github.com/josdemmers/Diablo4Companion/wiki/Frequently-asked-questions#how-to-enable-controller-support
