### ISSUE TITLE
TV support

### ISSUE THREAD

**Issue by matteospinaci17** [josdemmers/Diablo4Companion#74]
Hello, i'm playing Diablo 4 on a 42' full HD TV.
I followed the instructions, selecting full HD smf en preset, then importing a Gear preset from max roll (infinimist import Is not working, so i used corpse explosion instead), enabled overlay and controller support but the green/Red dots are not appearing next to affixes.
May the different DPI of a TV be the problem?

**Comment by josdemmers** [comment]
Should be fine if the resolution matches, you are using `1080p_SMF_en` I suppose?
Also make sure the ingame settings match the preset. 
SMF: S (SDR, so turn HDR off), MF (Medium font)

Are you using a controller or mouse/keyboard?
In case of a controller see this wiki entry to make sure it's configured correctly:
https://github.com/josdemmers/Diablo4Companion/wiki/Frequently-asked-questions#how-to-enable-controller-support

**Comment by matteospinaci17** [comment]
Ok thank you, i didnt configure the controller.
Is It correct that the dots refresh every few seconds?

**Comment by josdemmers** [comment]
> Is It correct that the dots refresh every few seconds?

You mean that it takes a few seconds when you switch to another item before the dots refresh?

**Comment by josdemmers** [comment]
Everything solved I suppose? If you have any other question or issue you can also join the Discord at https://discord.gg/NTZu8Px

**Comment by matteospinaci17** [comment]
Yes, thank you so much for developing this tool!
