### ISSUE TITLE
Item Tooltip Not working

### ISSUE THREAD

**Issue by wesm-work** [josdemmers/Diablo4Companion#77]
Just updated to V2.3 and now there is no tooltip dots showing up, worked before updating.

**Comment by josdemmers** [comment]
The images used to detect the tooltip have been changed in v2.3.
If you go to settings and update your preset it works again.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/5ca57bce-37a4-4485-a47b-126d429a7654)

**Comment by wesm-work** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/84863857/a5711537-a5ba-4e7e-876e-be404485c70d)

Mine is greyed out

**Comment by wesm-work** [comment]
You're awesome, thank you
