### ISSUE TITLE
S3 Update ?

### ISSUE THREAD

**Issue by lnksilver5** [josdemmers/Diablo4Companion#78]
hello, i tried to relaunch this great tool today to check some values on my druid, and nothing is displaying
I deleted and re-downloaded the latest release and all the Mapping for all the affixes are missing weirdly. Was working perfectly in S2
Is there a quick fix to this on my side or should I wait for an S3 Update ?
Have a good day :)

**Comment by josdemmers** [comment]
I'm waiting for the d4data repo to get the latest data. After that I can release a new version with the latest affixes and sigils.

However v2.4.3.0 should still work, although you will not see any affixes that have been changed/added in season 3 yet.
If you don't have any mappings go to settings and download the latest system preset matching your resolution. That will add all the mappings.

**Comment by lnksilver5** [comment]
no worries, i will wait for your update for S3, this is the best tool that saved my mental health in S2 :)
Enjoy your coffee on ko-fi 💓

**Comment by josdemmers** [comment]
Thanks for the support, appreciate it!
If you have problems when the S3 update is released feel free to post here again, or you can join the Discord channel so we can troubleshoot the issue further.

**Comment by josdemmers** [comment]
Release v2.4.4.0 is now available for season 3.
