### ISSUE TITLE
Aspects Not Flagging

### ISSUE THREAD

**Issue by allcoast** [josdemmers/Diablo4Companion#79]
For some reason, the affixes are not being flagged like usual. Its like they are just not recognized as aspects.

**Comment by josdemmers** [comment]
System presets have received some updates. Can you try downloading the latest one matching your configuration?
If the update button is grayed out then you need to disable the overlay first.

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/94e38953-9f4e-4059-bf35-f997065721bc)

**Comment by moulesmariner** [comment]
I'm experiencing a similar issue, the suggest fix doesn't seem to impact it...

**Comment by josdemmers** [comment]
Just fixed it in the latest 1440p_SMF_en preset. The aspect icon was slightly changed with the season 3 update.
If you update the preset under settings it should work again.

**Comment by moulesmariner** [comment]
Just tested, can confirm this is now working as intended! Thank you and great effort on a super useful tool!!

![image](https://github.com/josdemmers/Diablo4Companion/assets/18125880/78577b6f-9cf0-43fd-a470-0f0bd9941b5b)

**Comment by xconwayx** [comment]
Could there potentially be the same fix for 1080_SMF_en? 

I upgraded to the latest version when it came out. I thought it was just me and I found this thread. Per your suggestion up top, I downloaded a new copy and I still experience the same issue. I wish I could just change my graphics, but my card is too old. 

![D4](https://github.com/josdemmers/Diablo4Companion/assets/40808577/72280b46-6c1a-4b05-bdec-5c4e47d07160)

**Comment by josdemmers** [comment]
@xconwayx The fix here was for the aspect. Yours looks like something else. Possible a brightness issue?
Does your ingame setting look like this?
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/aa09d1be-9774-4024-9e18-b4e096429cc3)

If you want you can join the Discord channel: https://discord.gg/thgl
Makes it easier to troubleshoot your issue further.
