### ISSUE TITLE
Hello...where is the Rogue Imbuement Skills ?

### ISSUE THREAD

**Issue by billabonGS4** [josdemmers/Diablo4Companion#8]
Example: 
Rogue, Helm, " Ranks of Poison Imbuement " its not there ? Did i miss something ?

**Comment by billabonGS4** [comment]
> 

It would be nice to make a youtube video with a step by step explanation. There are people like me who are disabled and need a little more help than people who have a very high IQ. Would be nice if you also think of the stupid people.
I tried to change the preset, I also changed it in the program but nothing happened..

**Comment by josdemmers** [comment]
Do you see anything on the debug view?
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/748dc8b0-5baf-4ddc-90df-a5cb82d9b3b7)

**Comment by billabonGS4** [comment]
Sometimes I see an image and sometimes nothing at all and when I see something the image refreshes very slowly or not at all

**Comment by josdemmers** [comment]
The debug shows the detected tooltip. Make sure the overlay is turned on and that diablo is running.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/49427617-eeef-46d9-ac17-1552730dca38)

If the debug view still does not show anything then your resolution is not yet supported.
You can either create one yourself or wait till someone else does. System presets created by others will be shared when available so everyone can use it.

Also remember the app is in early development. There will be bugs in the coming weeks.

**Comment by billabonGS4** [comment]
I wanted to bring a short update to my problem. I downloaded the latest update from you and everything works as it should. Good work !

**Comment by josdemmers** [comment]
That's good to hear. Thanks for the feedback!
