### ISSUE TITLE
"critical strike chance" is filtering the other types

### ISSUE THREAD

**Issue by farukzahra** [josdemmers/Diablo4Companion#81]
"critical strike chance" is filtering the other types , eg. "critical strike chance against .."

**Comment by josdemmers** [comment]
You can solve that by adding the similar affixes as well and mark them as red.
https://github.com/josdemmers/Diablo4Companion/wiki/Frequently-asked-questions#how-to-ignore-similar-affixes

**Comment by farukzahra** [comment]
I understood, but I only imported a build from maxroll, so I believe that the default behavior, everything that is not imported should come, import as red

**Comment by josdemmers** [comment]
Unfortunately there are currently 300+ affixes. Adding them all would make the app really slow. Soo slow it's no longer usable.

Only way to change this is when OCR is fully implemented. But that is currently not yet ready for release.

**Comment by josdemmers** [comment]
@farukzahra Latest tests are looking good for OCR. This problem will be solved with the v3 release later this month.

**Comment by josdemmers** [comment]
Readme and wiki updated for v3. Version 3 is now available for download.
