### ISSUE TITLE
Imported Maxroll Build Contains Unknown Affix

### ISSUE THREAD

**Issue by morelandjo** [josdemmers/Diablo4Companion#82]
Tried uploading a bunch of maxroll builds to test, getting some errors, log doesn't specify which builds were the problem so here's all the ones I tried to import:

https://maxroll.gg/d4/planner/4f1r6091#5
https://maxroll.gg/d4/planner/eeau0ocn#8
https://maxroll.gg/d4/planner/ek1pb0rq#6
https://maxroll.gg/d4/planner/qiy909ya#1
https://maxroll.gg/d4/planner/qu8v0hvo#7
https://maxroll.gg/d4/planner/um3xz0t1#10

![log](https://github.com/josdemmers/Diablo4Companion/assets/11637260/e8a9f0a6-9f59-4fc5-8b77-ba4186112e72)

**Comment by josdemmers** [comment]
Thank you for the report. Going to address those issues the following days.
Besides the messages in your log you could also get an:
`Imported Maxroll build contains unknown itemtype id: 123`
Please report those as well when you notice them.

**Comment by josdemmers** [comment]
Fixed the above builds in v2.5.3.0
