### ISSUE TITLE
Dots in wrong position using 4k monitor downscaled to 2k

### ISSUE THREAD

**Issue by matteospinaci17** [josdemmers/Diablo4Companion#85]
Hello, i' using the latest release on a 4k monitor with resolution set to 2560x1440, the preset is 1440p_SMF_en
I tried to use the 4k present but my monitor doesn't support HDR.
![d4comp](https://github.com/josdemmers/Diablo4Companion/assets/44896883/b93852d1-6cd7-4b9f-a222-fec7762373ff)
As you can see in the screenshot the dots are at the center of the screen, is something wrong with my configuration?

**Comment by matteospinaci17** [comment]
The dots are woking, just appearing in the wrong position

**Comment by josdemmers** [comment]
Don't have any 4k screens myself to troubleshoot this. But my guess is it's related to your resolution or scaling settings.

Are you monitor and Diablo both set to the same resolution?
Or maybe do you use multiple monitors with different resolutions/scaling settings?

**Comment by matteospinaci17** [comment]
I have a 4k monitor set to 2k.
Diablo is set to the same resolution of monitor by default, i dont think it's possible to have another one (the select dropdown is locked for me).
However setting the monitor to full hd with the 1080p preset fix this, it a problem related to my specific configuration (4k monitor downscaled 2k resolution with 1440p_SMF preset).

**Comment by josdemmers** [comment]
Strange that downscaling to 1080p works and 1440p not. Do you notice any differences between the two in your windows settings? To what value is the scaling set for 1080p and 1440p?

And another question to troubleshoot this. Do you have one or two monitors connected to your pc?

**Comment by matteospinaci17** [comment]
Problem solved: the windows scaling has to be set 100%.
Previosly i was using 150% on 2k resolution.
Thank you for your help!
