### ISSUE TITLE
green/red dots are no longer shown for affixes

### ISSUE THREAD

**Issue by spotlight2001** [josdemmers/Diablo4Companion#89]
Hi,

on first use i have had the green/red dots next to the affixes

a day later only red dots next to the aspects appeared

a day later no green/red dots are showing up

companion overlay is activated
1440p_SMF_en is being used
affixes are configured in the app

with new version 2.6.0 i have the same results

in diablo 4 i have 1440p, NO HDR, medium font size

**Comment by josdemmers** [comment]
Are you using any apps that influence you game graphics, for example ReShade or similar?

And I would check if your brightness settings match the defaults. Should be close to this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/f0376794-cf7b-40ba-8403-b70f33810d5c)

**Comment by josdemmers** [comment]
Also updating the system preset to have the latest images might help:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/5f117d3e-8a4b-4d40-8eaf-8dee681681cb)

System presets updates or more frequent at the beginning of the season but now it still can get updates once a week.

**Comment by spotlight2001** [comment]
@josdemmers reduce brightness solved the problem. Thanks :)
i suggest to put this to the wiki troubleshooting section :)

**Comment by josdemmers** [comment]
@spotlight2001 There can be a lot of reasons the green/red dots do not show up. I'll list some of the common causes in the wiki.
