### ISSUE TITLE
Game have micro stutters with D4Companion overlay

### ISSUE THREAD

**Issue by SilverSaw** [josdemmers/Diablo4Companion#90]
I do not know where is the issue, but when D4Companion overlay is turned on game start to stutter. FPS is not really dropping, but i can see the stuttering.  After i disable D4Companion everything is back to normal.

**Comment by josdemmers** [comment]
Hi @SilverSaw the app can be heavy on your cpu when scanning for item tooltips.
To improve performance you can use the icon in the top left corner to turn it on/off.
But there are also Hotkeys available in the settings menu to turn the app quickly on/off.
The Hotkeys make it easy to only turn the app on when checking your inventory.

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/18b814b4-0b44-4ec3-9c36-340cc8d3a90e)

If you want to keep the overlay on at all times you could check if there are any other overlays active on your pc that could interfere.

**Comment by SilverSaw** [comment]
Thanks for the suggestion about hotkeys i have 7600x and was thinking that it is enough to handle such a program. Also i do not see any unusual load on the cpu graph. It is strange, but benchmarking the game also do not show me any unusual change on the latency or fps. My fps is usually capped at 140-150 with all settings on Max and with the D4Companion it drops sometimes to 130-150 which is not. Latency is between 6 and 8ms. I did not measure min and max fps, maybe there is difference.

If it is turned off by hotkey micro stutters are not observed, but it is less convenient to turn your app on and off every time i am inspecting inventory.

**Comment by josdemmers** [comment]
The overlay is limited at 60 FPS, maybe that can cause issues for your PC?
I'll create a test version and set it at 200 FPS, then it never reaches your cap.
Just for testing purpose to see if this has any effect.

**Comment by josdemmers** [comment]
@SilverSaw You can try this version if you want:
https://filebin.net/5b5yes0ic2knw7wh

Let me know if it helps then I can add it as a setting in a future version.

**Comment by SilverSaw** [comment]
Hi @josdemmers i have just tried your newly attached 2.7.1 200fps version and stuttering is still the same i have tried with initial version 2.7.0 to limit my max foreground fps from the game to 60fps and stuttering it is getting worse. 

Actually after some more testing also with the initial version i have tested 2.7.0, if D4Companion is open on the background even without overlay turned on stuttering is still in the game. When i completely exit the D4Copanion application, stuttering is gone, and this is happening with overlay off not only when i turn on overlay like i said early. It seems to be something from the application itself. I have modified a bit my latency graph trying to see the stuttering and now it can be clearly seen.

Example of my latency graph when D4Companion app is opened in the background with or without overlay turned on. This stuttering is on this small bumps in the graph.
![with d4comp](https://github.com/josdemmers/Diablo4Companion/assets/1420683/d95442bc-de84-4a36-b3a9-e978f45caea6)

Example of my latency graph when D4Companion app is closed. We can clearly see how straight it is.
![without d4comp](https://github.com/josdemmers/Diablo4Companion/assets/1420683/b7ae30b2-bd9e-4f01-862d-ac1561634f3b)

**Comment by SilverSaw** [comment]
After some more testing i have found actually that when overlay is turned on, stuttering is still in the game but somehow less. When i played a bit more with the graph height, it approved my subjective feeling.

without d4comp
![without d4comp](https://github.com/josdemmers/Diablo4Companion/assets/1420683/c6385726-35e1-4c48-8855-145abc417a0c)

with d4comp overlay off
![with d4comp overlay off](https://github.com/josdemmers/Diablo4Companion/assets/1420683/21007bd6-411f-4b9a-8354-7853b5ad22c5)

with d4comp overlay on
![with d4comp overlay on](https://github.com/josdemmers/Diablo4Companion/assets/1420683/efb9784d-48f4-4ee5-b9a6-fde04a7464b9)

**Comment by josdemmers** [comment]
Are you able to measure the interval between those small stuttering bumps? Are those around 50ms?

**Comment by SilverSaw** [comment]
This is the results when i analyze the graph for min/max milliseconds during every test.
![latency](https://github.com/josdemmers/Diablo4Companion/assets/1420683/32625011-5985-49a9-be28-329bfdab0f7a)

There is no big of a difference on min/max milliseconds, but feeling for stuttering is big when app UI is opened.

**Comment by josdemmers** [comment]
Performance does not seem to be the issue here. More than enough power in that pc.

Because the stuttering bumps happen at a steady interval it must be related to the update frequency of the app.
The app uses low level winapi calls for the Diablo window and screen data. If other apps are also using winapi calls they could interfere with each other.

Could you try turning off any other monitoring and overlay applications and only run diablo and the companion app. The less programs are active the better.

Then try if you still notice any stuttering ingame.

**Comment by josdemmers** [comment]
Too bad, then I'm still not sure what part of the program is causing your issue.
Want to do another test?

https://filebin.net/almhraldmw6uivgw

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/52d12d06-d1c1-4a85-84dd-4c90111636c9)

Increased the interval by 10x. Could you try if the interval between the stuttering is still the same as in your previous screenshot or that it's a lot longer now?

**Comment by SilverSaw** [comment]
Interval is still the same, i think. I feel same stuttering again with Diablo4Companion_v2.7.1.0-550interval
![Untitled](https://github.com/josdemmers/Diablo4Companion/assets/1420683/01ffa2c0-e477-4e71-82f3-43eedb08a0cd)

**Comment by SilverSaw** [comment]
Okay, i think i found if it is coming from my Mnitor G-Sync module.

with g-sync on and d4comp opened in the background
![with g-sync on](https://github.com/josdemmers/Diablo4Companion/assets/1420683/c59b6d5e-f3c5-4304-93fb-0cb6caa7085b)

with g-sync off and d4comp opened in the background
![with g-sync off](https://github.com/josdemmers/Diablo4Companion/assets/1420683/69b5a5e8-6383-4f6c-a9ec-d4b7da8033e9)

For some reason, d4comp is not working with g-sync and g-sync is like disabled when d4comp is opened, maybe they interfere somehow. I am unable to play without g-sync because of this stutters, when g-sync is turned on is buttery smooth. 

Workaround what i tested and working without stutetring:
1. turn off g-sync, 
2. cap my game fps to 120 something that my game never fell below so i do not need to use g-sync and then 
3. turn on d4comp

**Comment by josdemmers** [comment]
Here is the final test: https://filebin.net/htx3kdr9laibsfjh
This time with no overlay.

**Comment by SilverSaw** [comment]
I can confirm that with [Diablo4Companion_v2.7.1.0-nooverlay.zip](https://filebin.net/htx3kdr9laibsfjh/Diablo4Companion_v2.7.1.0-nooverlay.zip) opened in the background, and g-sync on, there is no stuttering at all.

**Comment by josdemmers** [comment]
Looks like this is an issue for many apps, for example:
https://www.reddit.com/r/gsync/comments/rf79a4/why_exactly_does_gsync_cause_major_lag_in_certain/
https://github.com/dotnet/wpf/issues/2294

One thing mentioned in those topics is
> You can disable GSync on a per app basis in the NVIDIA control panel.

Maybe you can use that to keep it active for Diablo but disable it for the Companion App? Not sure it works, but it's worth a try.

Besides that it does not look like I can fix this any time soon. The linked GitHub issue is from 2019 and still does not have a solution.

**Comment by SilverSaw** [comment]
I just tested, i have placed local settings just for the D4Companion.exe app for g-sync to be turned off and for diablo4 for g-sync to be turned on, and it's not working, there is still the same stuttering. 

Only working if global settings for g-sync are turned off, that means not to use g-sync at all for diablo4.

**Comment by josdemmers** [comment]
Too bad, that was the last workaround I could think of.
Looks like your only option for now is to completely disable g-sync.
