### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by XxTroy90xX** [josdemmers/Diablo4Companion#99]
I have tried almost everything to get this app to work for me and i cannot for the life of me to get it to work. i have people in my discord that have the same app and tried to walk me through the process of making it work and still does not work for me. I have tried to reinstall and changed settings for the resolution multiple times and even imported a build and still didn't work no Green or Red dots but the overlay icon does appear. IF there is a video guide i would greatly appreciate a link to it because pictures are obviously not working for me.

**Comment by Saharash** [comment]
Make sure to have correctly set the options writed in the resolution you choose

It should be Font Scale to medium mostly, if you have HDR choose the good option, if no chose the good one, and adjust the luminosity to bit higher(60) as show in tutorial

**Comment by josdemmers** [comment]
@XxTroy90xX There is no video at the moment. But we can do some troubleshooting if you join the discord (select the diablo role and you will see the relevant channels). That works easier than using github.

**Comment by josdemmers** [comment]
No response, closed. Feel free to join Discord if you want to troubleshoot.
https://th.gl/discord
